### PR TITLE
Create go.yml

### PR DESCRIPTION
**Pull request by ntangy**
Creates yml to configure Github actions to run tests on every PR to master and merge to master, replacing travis CI

### CODE REVIEW

**Review by webbbarker — COMMENTED** [review]
@ntangy Is this PR intended to fully replace TravisCI, or just the status checks?  I believe @amagana3 setup some `GoReleaser` items to publish signed artifacts on commits to `master`.

**Comment by ntangy** [comment]
> @ntangy Is this PR intended to fully replace TravisCI, or just the status checks? I believe @amagana3 setup some `GoReleaser` items to publish signed artifacts on commits to `master`.

Yes the intent was to replace travis CI, I don't think travis CI does anything more than running tests now and we have a separate Github Action in place that handles the go releaser stuff. @amagana3 is this about right?

**Comment by amagana3** [comment]
@ntangy Yep! That sounds right 👍🏼

**Review by webbbarker — APPROVED** [review]
👍

**Pull request merged**
